apiVersion: apps/v1
kind: Deployment
metadata:
  name: find-me
  labels:
    app: find-me
spec:
  replicas: 1
  selector:
    matchLabels:
      app: find-me
  template:
    metadata:
      labels:
        app: find-me
    spec:
      containers:
      - name: find-me
        image: philipfischbacher/gke-training-find-me:v1
        imagePullPolicy: Always
